import type { ComponentType } from 'react';
import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiTailwindcss,
  SiVite,
  SiPhp,
  SiMysql,
  SiMongodb,
  SiWordpress,
  SiWoocommerce,
  SiGit,
  SiGithub,
  SiCanvas,
  SiLinux,
} from 'react-icons/si';
import { TbBrandCpp, TbBrandWindows } from 'react-icons/tb';
import { Database, FileSpreadsheet, Cpu, Search, Film, FileText, Globe } from 'lucide-react';

export type IconComponent = ComponentType<{ size?: number | string; className?: string }>;

export const techIcons: Record<string, IconComponent> = {
  html5: SiHtml5,
  css3: SiCss,
  javascript: SiJavascript,
  typescript: SiTypescript,
  reactjs: SiReact,
  tailwindcss: SiTailwindcss,
  vite: SiVite,
  php: SiPhp,
  mysql: SiMysql,
  mongodb: SiMongodb,
  wordpress: SiWordpress,
  woocommerce: SiWoocommerce,
  git: SiGit,
  github: SiGithub,
  canva: SiCanvas,
  linux: SiLinux,
  windows: TbBrandWindows,
  cpp: TbBrandCpp,
  msaccess: Database,
  msoffice: FileSpreadsheet,
  genai: Cpu,
  seo: Search,
  technicalseo: Search,
  restapi: Globe,
  restapis: Globe,
  currencyapi: Globe,
  videoediting: Film,
  inpage: FileText,
  elementor: Globe,
};

export const techColors: Record<string, string> = {
  html5: '#E34F26',
  css3: '#1572B6',
  javascript: '#F7DF1E',
  typescript: '#3178C6',
  reactjs: '#61DAFB',
  tailwindcss: '#06B6D4',
  vite: '#646CFF',
  php: '#777BB4',
  mysql: '#4479A1',
  mongodb: '#47A248',
  wordpress: '#21759B',
  woocommerce: '#96588A',
  git: '#F05032',
  github: '#181717',
  canva: '#00C4CC',
  linux: '#FCC624',
  windows: '#0078D4',
  cpp: '#00599C',
  msaccess: '#A4373A',
  msoffice: '#D83B01',
  genai: '#10A37F',
  seo: '#34A853',
  technicalseo: '#4285F4',
  restapi: '#10B981',
  restapis: '#10B981',
  currencyapi: '#F59E0B',
  videoediting: '#EC4899',
  inpage: '#6366F1',
  elementor: '#92003B',
};

export const FallbackIcon: IconComponent = Globe;

